#!/usr/bin/env python3
"""Comprehensive keyboard shortcuts dictionary for DaVinci Resolve."""

from typing import Dict


def get_keyboard_shortcuts() -> Dict[str, str]:
    """Get a comprehensive dictionary of DaVinci Resolve keyboard shortcuts."""
    return {
        # === PLAYBACK / NAVIGATION ===
        "play_pause": "Space",
        "stop": "K",
        "play_forward": "L",
        "play_reverse": "J",
        "fast_forward": "Shift+L",
        "fast_reverse": "Shift+J",
        "step_forward": "Right Arrow",
        "step_backward": "Left Arrow",
        "step_1_second_forward": "Shift+Right Arrow",
        "step_1_second_backward": "Shift+Left Arrow",
        "go_to_start": "Home",
        "go_to_end": "End",
        "go_to_first_frame": ";",
        "go_to_last_frame": "'",
        "loop_toggle": "Ctrl+/",
        "play_around_current": "/",
        "play_around_in": "Alt+Space",
        "play_around_out": "Shift+Space",
        "previous_clip": "Up Arrow",
        "next_clip": "Down Arrow",
        "go_to_prev_keyframe": "[",
        "go_to_next_keyframe": "]",
        # === MARKS ===
        "set_mark_in": "I",
        "set_mark_out": "O",
        "mark_clip": "X",
        "go_to_mark_in": "Shift+I",
        "go_to_mark_out": "Shift+O",
        "clear_mark_in": "Alt+I",
        "clear_mark_out": "Alt+O",
        "clear_mark_in_out": "Alt+X",
        # === MARKERS ===
        "add_marker": "M",
        "add_modify_marker": "Ctrl+M",
        "modify_marker": "Shift+M",
        "delete_marker": "Alt+M",
        "go_to_next_marker": "Shift+Down Arrow",
        "go_to_prev_marker": "Shift+Up Arrow",
        # === EDITING ===
        "cut_at_playhead": "Ctrl+B",
        "split_clip": "Ctrl+\\",
        "join_clip": "Alt+\\",
        "ripple_delete": "Delete",
        "delete_selected": "Backspace",
        "undo": "Ctrl+Z",
        "redo": "Ctrl+Shift+Z",
        "trim_start": "Shift+[",
        "trim_end": "Shift+]",
        "nudge_left": ",",
        "nudge_right": ".",
        "nudge_multiframe_left": "Shift+,",
        "nudge_multiframe_right": "Shift+.",
        "insert": "F9",
        "overwrite": "F10",
        "replace": "F11",
        "place_on_top": "F12",
        "ripple_overwrite": "Shift+F10",
        "fit_to_fill": "Shift+F11",
        "append_to_end": "Shift+F12",
        "copy": "Ctrl+C",
        "cut": "Ctrl+X",
        "paste": "Ctrl+V",
        "create_subclip": "Alt+B",
        "add_transition": "Ctrl+T",
        "add_video_transition": "Alt+T",
        "add_audio_transition": "Shift+T",
        # === SELECTION ===
        "select_all": "Ctrl+A",
        "deselect_all": "Ctrl+Shift+A",
        "select_forward": "Y",
        "select_backward": "Ctrl+Y",
        "select_nearest_edit": "V",
        "select_blade": "B",
        # === TOGGLES ===
        "source_timeline_viewer": "Q",
        "extract_current_node": "E",
        "enable_disable_clip": "D",
        "match_frame": "F",
        "add_flag": "G",
        "toggle_hand_selection": "H",
        "cinema_viewer": "P",
        "dynamic_trim_mode": "W",
        "trim_mode": "T",
        "edit_point_type": "U",
        "normal_edit_mode": "A",
        "snapping": "N",
        "slip_slide_mode": "S",
        "audio_scrubbing": "Shift+S",
        # === VIEW ===
        "zoom_in": "Ctrl+=",
        "zoom_out": "Ctrl+-",
        "zoom_in_viewer": "+",
        "zoom_out_viewer": "-",
        "fit_timeline": "Shift+Z",
        "fullscreen_viewer": "Shift+F",
        "enhanced_viewer": "Alt+F",
        "cinema_viewer_ctrl": "Ctrl+F",
        "expand_display": "F4",
        "left_display": "1",
        "right_display": "2",
        "display_red_channel": "R",
        "display_z_buffer": "Z",
        "display_full_color": "C",
        "split_screen": "Ctrl+Alt+W",
        "video_scopes": "Ctrl+Shift+W",
        "retime_controls": "Ctrl+R",
        "freeze_frame": "Shift+R",
        # === NODES (Color Page) ===
        "disable_current_node": "Ctrl+D",
        "disable_all_nodes": "Alt+D",
        "bypass_all_grades": "Shift+D",
        "add_serial_node": "Alt+S",
        "add_parallel_node": "Alt+P",
        "add_layer_node": "Alt+L",
        "add_serial_node_before": "Alt+Q",
        "add_outside_node": "Alt+C",
        "add_splitter_combiner": "Alt+Y",
        "reset_grades_notes": "Ctrl+Home",
        "previous_node": "Shift+Alt+;",
        "next_node": "Shift+Alt+'",
        "apply_grade_one_prior": "=",
        "apply_grade_two_prior": "-",
        "auto_color": "Alt+A",
        "highlight": "Shift+H",
        "add_version": "Ctrl+Y",
        "grab_still": "Ctrl+Alt+G",
        # === APPLICATION ===
        "import_media": "Ctrl+I",
        "save_project": "Ctrl+S",
        "export_project": "Ctrl+E",
        "new_timeline": "Ctrl+N",
        "new_bin": "Ctrl+Shift+N",
        "project_settings": "Shift+9",
        "preferences": "Ctrl+,",
        "keyboard_customization": "Ctrl+Alt+K",
        "quit": "Ctrl+Q",
        # === PAGES ===
        "media_page": "Shift+2",
        "cut_page": "Shift+3",
        "edit_page": "Shift+4",
        "fusion_page": "Shift+5",
        "color_page": "Shift+6",
        "fairlight_page": "Shift+7",
        "deliver_page": "Shift+8",
        # === AUDIO ===
        "volume_down_1db": "Ctrl+Alt+-",
        "volume_up_1db": "Ctrl+Alt+=",
        "toggle_video_audio_separate": "Alt+U",
        # === MEMORY (Color Page) ===
        "load_memory_a": "Ctrl+1",
        "save_memory_a": "Alt+1",
        "load_memory_b": "Ctrl+2",
        "save_memory_b": "Alt+2",
        "load_memory_c": "Ctrl+3",
        "save_memory_c": "Alt+3",
        "load_memory_d": "Ctrl+4",
        "save_memory_d": "Alt+4",
    }
